#!/usr/bin/env bash
# Updates server, installs Nginx and configures 

sudo apt-get -y update
sudo apt-get -y install nginx
sudo bash -c "echo 'Hello World!'> /var/www/html/index.nginx-debian.html"
sudo service nginx start
