#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend felixfrz.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 168263-web-01 52.91.136.113:80
        server 168263-web-02 35.153.17.236:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart

